---
name: Lingua-Stem-Snowball
version: 0.94_3
author:
  - 'Marvin Humphrey <marvin at rectangular dot com>'
abstract: Perl interface to Snowball stemmers.
license: perl
requires:
  Test::More: 0
provides:
  Lingua::Stem::Snowball:
    file: lib/Lingua/Stem/Snowball.pm
    version: 0.94_3
generated_by: Module::Build version 0.2611
